apiVersion: v2
name: postgres-helm
description: Helm chart for deploying PostgreSQL using the agynio service-base library.
type: application
version: 0.1.1
appVersion: "16.6"
home: https://github.com/agynio/postgres-helm
sources:
  - https://github.com/agynio/postgres-helm
dependencies:
  - name: service-base
    version: ">=0.1.4 <1.0.0"
    repository: oci://ghcr.io/agynio/charts
