{{- if and (not .Values.auth.existingSecret) (.Values.postgres.password) -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "service-base.fullname" . }}
  labels:
{{ include "service-base.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{ include "postgres-helm.passwordKey" . }}: {{ .Values.postgres.password | quote }}
{{- end -}}
